// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeaBaseAPI;

#nullable disable

namespace SeaBaseAPI.Migrations
{
    [DbContext(typeof(SeaBaseContext))]
    [Migration("20240101223150_update submersible condition")]
    partial class updatesubmersiblecondition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeaBaseAPI.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeployed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubmersibleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmersibleId");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("SeaBaseAPI.Submersible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Condition")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeployed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PilotId")
                        .HasColumnType("integer");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("Submersibles");
                });

            modelBuilder.Entity("SeaBaseAPI.Personnel", b =>
                {
                    b.HasOne("SeaBaseAPI.Submersible", null)
                        .WithMany("Crew")
                        .HasForeignKey("SubmersibleId");
                });

            modelBuilder.Entity("SeaBaseAPI.Submersible", b =>
                {
                    b.HasOne("SeaBaseAPI.Personnel", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("SeaBaseAPI.Submersible", b =>
                {
                    b.Navigation("Crew");
                });
#pragma warning restore 612, 618
        }
    }
}
